# Generated by Django 5.2.5 on 2025-10-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مقصد')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('continent', models.CharField(choices=[('asia', 'آسیا'), ('europe', 'اروپا'), ('africa', 'آفریقا'), ('north_america', 'آمریکای شمالی'), ('south_america', 'آمریکای جنوبی'), ('oceania', 'اقیانوسیه'), ('middle_east', 'خاورمیانه')], max_length=20, verbose_name='قاره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('best_time_to_visit', models.CharField(max_length=200, verbose_name='بهترین زمان بازدید')),
                ('visa_requirements', models.TextField(blank=True, verbose_name='شرایط ویزا')),
                ('climate', models.TextField(blank=True, verbose_name='آب و هوا')),
                ('culture', models.TextField(blank=True, verbose_name='فرهنگ و آداب و رسوم')),
                ('featured_image', models.ImageField(upload_to='destinations/', verbose_name='تصویر شاخص')),
                ('is_popular', models.BooleanField(default=False, verbose_name='محبوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='متا عنوان')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='متا توضیحات')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقصد',
                'verbose_name_plural': 'مقاصد',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'تصویر مقصد',
                'verbose_name_plural': 'تصاویر مقاصد',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='destination_galleries', to='destinations.destinationimage', verbose_name='گالری تصاویر'),
        ),
    ]
