# Generated by Django 5.2.5 on 2025-10-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('status', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اشتراک')),
            ],
            options={
                'verbose_name': 'مشترک خبرنامه',
                'verbose_name_plural': 'مشترکین خبرنامه',
            },
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
