# Generated by Django 5.2.5 on 2025-10-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newslettersubscriber_delete_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'تماس', 'verbose_name_plural': 'تماس\u200cها'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
