# Generated by Django 5.2.5 on 2025-10-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_contact_options_remove_contact_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
