# Generated by Django 5.2.5 on 2025-10-30 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='چکیده')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='تصویر شاخص')),
                ('page_type', models.CharField(choices=[('about', 'درباره ما'), ('service', 'خدمات'), ('policy', 'قوانین'), ('contact', 'تماس'), ('custom', 'سفارشی')], default='custom', max_length=20, verbose_name='نوع صفحه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='نمایش در منو')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='نمایش در فوتر')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب در منو')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='متا عنوان')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='متا توضیحات')),
                ('meta_keywords', models.CharField(blank=True, max_length=200, verbose_name='کلمات کلیدی')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان بخش')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='page-sections/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'verbose_name': 'بخش صفحه',
                'verbose_name_plural': 'بخش\u200cهای صفحات',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'published_date'], name='pages_page_status_1e5a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['page_type', 'show_in_menu'], name='pages_page_page_ty_0d9d7e_idx'),
        ),
    ]
