# Generated by Django 5.2.5 on 2025-10-30 17:34

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_user'),
        ('pages', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان لینک')),
                ('url', models.CharField(max_length=500, verbose_name='آدرس')),
                ('is_external', models.BooleanField(default=False, verbose_name='لینک خارجی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'لینک صفحه',
                'verbose_name_plural': 'لینک\u200cهای صفحات',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_order', 'title'], 'permissions': [('can_manage_pages', 'می\u200cتواند صفحات را مدیریت کند'), ('can_publish_pages', 'می\u200cتواند صفحات را منتشر کند'), ('can_edit_private_pages', 'می\u200cتواند صفحات خصوصی را ویرایش کند')], 'verbose_name': 'صفحه', 'verbose_name_plural': 'صفحات'},
        ),
        migrations.AddField(
            model_name='page',
            name='access_level',
            field=models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی - فقط ادمین\u200cها'), ('premium', 'ویژه - کاربران خاص')], default='public', max_length=20, verbose_name='سطح دسترسی'),
        ),
        migrations.AddField(
            model_name='page',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='کاربران مجاز برای ویرایش این صفحه', related_name='editable_pages', to=settings.AUTH_USER_MODEL, verbose_name='ویراستاران'),
        ),
        migrations.AddField(
            model_name='page',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا'),
        ),
        migrations.AddField(
            model_name='page',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='pages', to='blog.post', verbose_name='پست\u200cهای مرتبط'),
        ),
        migrations.AddField(
            model_name='page',
            name='related_tours',
            field=models.ManyToManyField(blank=True, related_name='pages', to='tours.tour', verbose_name='تورهای مرتبط'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحات ویژه'),
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pages/thumbnails/', verbose_name='تصویر کوچک'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='layout',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('image_left', 'تصویر چپ'), ('image_right', 'تصویر راست'), ('full_width', 'تمام عرض'), ('columns_2', 'دو ستونه'), ('columns_3', 'سه ستونه')], default='default', max_length=20, verbose_name='طرح\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('about', 'درباره ما'), ('service', 'خدمات'), ('policy', 'قوانین'), ('contact', 'تماس'), ('news', 'اخبار'), ('promotion', 'تخفیف\u200cها'), ('tour_info', 'اطلاعات تورها'), ('custom', 'سفارشی')], default='custom', max_length=20, verbose_name='نوع صفحه'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='محتوا'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['access_level', 'status'], name='pages_page_access__803b08_idx'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='pages.page'),
        ),
    ]
