# Generated by Django 5.2.5 on 2025-10-30 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_approved_by_post_approved_date_and_more'),
        ('pages', '0002_pagelink_alter_page_options_page_access_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blog_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_source', to='blog.post', verbose_name='پست مرتبط در بلاگ'),
        ),
        migrations.AddField(
            model_name='page',
            name='publish_to_blog',
            field=models.BooleanField(default=False, verbose_name='انتشار در بلاگ'),
        ),
    ]
