# Generated by Django 5.2.5 on 2025-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام خدمت')),
                ('service_type', models.CharField(choices=[('flight', 'پرواز'), ('hotel', 'هتل'), ('visa', 'ویزا'), ('insurance', 'بیمه مسافرتی'), ('transfer', 'ترانسفر فرودگاهی'), ('tour_guide', 'راهنمای تور'), ('car_rental', 'اجاره ماشین')], max_length=20, verbose_name='نوع خدمت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('features', models.TextField(help_text='هر ویژگی در یک خط', verbose_name='ویژگی\u200cها')),
                ('price_range', models.CharField(blank=True, max_length=100, verbose_name=' محدوده قیمت')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'name'],
            },
        ),
    ]
