# Generated by Django 5.2.5 on 2025-10-29 20:15

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_level', models.CharField(choices=[('normal', 'کاربر معمولی'), ('writer', 'نویسنده'), ('admin', 'ادمین سایت'), ('super_admin', 'رییس (Super Admin)')], default='normal', max_length=15, verbose_name='سطح دسترسی')),
                ('bio', models.TextField(blank=True, help_text='حداکثر ۱۰۰۰ کاراکتر', max_length=1000, verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, help_text='تصویر با ابعاد 200x200 پیکسل مناسب است', null=True, upload_to=accounts.models.user_profile_image_path, verbose_name='تصویر پروفایل')),
                ('birth_date', models.DateField(blank=True, help_text='فرمت: YYYY-MM-DD', null=True, verbose_name='تاریخ تولد')),
                ('phone_number', models.CharField(blank=True, help_text='مثال: 09123456789', max_length=15, null=True, verbose_name='شماره تلفن')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شغلی')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرکت/سازمان')),
                ('education_level', models.CharField(blank=True, choices=[('diploma', 'دیپلم'), ('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], max_length=20, null=True, verbose_name='سطح تحصیلات')),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته تحصیلی')),
                ('website', models.URLField(blank=True, help_text='آدرس کامل وبسایت', null=True, verbose_name='وبسایت شخصی')),
                ('github', models.URLField(blank=True, help_text='آدرس پروفایل GitHub', null=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, help_text='آدرس پروفایل LinkedIn', null=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, help_text='آدرس پروفایل Twitter', null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, help_text='آدرس پروفایل Instagram', null=True, verbose_name='Instagram')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['user_level'], name='accounts_us_user_le_af9f10_idx'), models.Index(fields=['created_date'], name='accounts_us_created_d0d06e_idx')],
            },
        ),
    ]
