# Generated by Django 5.2.5 on 2025-10-30 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='کدملی')),
                ('date_of_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, verbose_name='جنسیت')),
                ('passenger_type', models.CharField(choices=[('adult', 'بزرگسال'), ('child', 'کودک'), ('infant', 'نوزاد')], default='adult', max_length=10, verbose_name='نوع مسافر')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافرین',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10, verbose_name='شماره صندلی')),
                ('seat_class', models.CharField(choices=[('economy', 'اکونومی'), ('business', 'بیزینس'), ('first', 'فرست کلاس'), ('premium', 'پریمیوم')], default='economy', max_length=20, verbose_name='کلاس صندلی')),
                ('row', models.PositiveIntegerField(verbose_name='ردیف')),
                ('column', models.CharField(max_length=5, verbose_name='ستون')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='ویژگی\u200cها')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تغییرات قیمت')),
                ('is_available', models.BooleanField(default=True, verbose_name='قابل رزرو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'صندلی',
                'verbose_name_plural': 'صندلی\u200cها',
                'ordering': ['row', 'column'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تور')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.TextField(max_length=300, verbose_name='توضیح کوتاه')),
                ('tour_type', models.CharField(choices=[('one_way', 'تور یکطرفه'), ('round_trip', 'تور رفت و برگشت'), ('multi_city', 'تور چند شهری'), ('package', 'تور پکیج کامل')], max_length=20, verbose_name='نوع تور')),
                ('origin_city', models.CharField(max_length=100, verbose_name='شهر مبدأ')),
                ('destination_city', models.CharField(max_length=100, verbose_name='شهر مقصد')),
                ('duration_days', models.PositiveIntegerField(verbose_name='تعداد روزها')),
                ('duration_nights', models.PositiveIntegerField(verbose_name='تعداد شب\u200cها')),
                ('departure_datetime', models.DateTimeField(verbose_name='تاریخ و زمان حرکت')),
                ('return_datetime', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان برگشت')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت پایه')),
                ('child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت کودک')),
                ('infant_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت نوزاد')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت با تخفیف')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='ظرفیت کل')),
                ('available_capacity', models.PositiveIntegerField(verbose_name='ظرفیت باقیمانده')),
                ('min_travelers', models.PositiveIntegerField(default=1, verbose_name='حداقل مسافر')),
                ('max_travelers', models.PositiveIntegerField(default=50, verbose_name='حداکثر مسافر')),
                ('featured_image', models.ImageField(upload_to='tours/', verbose_name='تصویر اصلی')),
                ('includes', models.TextField(help_text='هر خدمت در یک خط', verbose_name='خدمات شامل')),
                ('excludes', models.TextField(help_text='هر مورد در یک خط', verbose_name='خدمات غیرشامل')),
                ('itinerary', models.TextField(verbose_name='برنامه سفر')),
                ('requirements', models.TextField(blank=True, verbose_name='ملزومات سفر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_instant_confirmation', models.BooleanField(default=True, verbose_name='تأیید فوری')),
                ('seat_selection_available', models.BooleanField(default=True, verbose_name='انتخاب صندلی فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تور',
                'verbose_name_plural': 'تورها',
                'ordering': ['departure_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی تور',
                'verbose_name_plural': 'دسته\u200cبندی تورها',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام وسیله نقلیه')),
                ('transport_type', models.CharField(choices=[('bus', 'اتوبوس'), ('train', 'قطار'), ('airplane', 'هواپیما'), ('cruise', 'کشتی'), ('minibus', 'مینی بوس'), ('car', 'خودرو شخصی')], max_length=20, verbose_name='نوع وسیله')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('facilities', models.TextField(blank=True, verbose_name='امکانات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='transportations/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'وسیله نقلیه',
                'verbose_name_plural': 'وسایل نقلیه',
            },
        ),
        migrations.CreateModel(
            name='SelectedReturnSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.passenger', verbose_name='مسافر')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.seat')),
            ],
            options={
                'verbose_name': 'صندلی برگشت انتخاب شده',
                'verbose_name_plural': 'صندلی\u200cهای برگشت انتخاب شده',
            },
        ),
        migrations.CreateModel(
            name='SelectedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_departure', models.BooleanField(default=True, verbose_name='صندلی رفت')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.passenger', verbose_name='مسافر')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.seat')),
            ],
            options={
                'verbose_name': 'صندلی انتخاب شده',
                'verbose_name_plural': 'صندلی\u200cهای انتخاب شده',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخفیف')),
                ('code', models.CharField(help_text='کد قابل استفاده برای مشتریان', max_length=20, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='مقدار تخفیف')),
                ('apply_to', models.CharField(choices=[('all_tours', 'همه تورها'), ('specific_tours', 'تورهای خاص'), ('tour_categories', 'دسته\u200cبندی تورها')], default='all_tours', max_length=20, verbose_name='اعمال بر')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='حداکثر تخفیف')),
                ('min_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حداقل مبلغ سفارش')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = نامحدود', verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('valid_from', models.DateField(verbose_name='اعتبار از')),
                ('valid_to', models.DateField(verbose_name='اعتبار تا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_public', models.BooleanField(default=True, verbose_name='نمایش عمومی')),
                ('tours', models.ManyToManyField(blank=True, to='tours.tour', verbose_name='تورهای مشخص')),
                ('categories', models.ManyToManyField(blank=True, to='tours.tourcategory', verbose_name='دسته\u200cبندی\u200cها')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=20, unique=True, verbose_name='کد رزرو')),
                ('adult_count', models.PositiveIntegerField(default=1, verbose_name='تعداد بزرگسال')),
                ('child_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کودک')),
                ('infant_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نوزاد')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پایه')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مالیات')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تخفیف')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تأیید شده'), ('cancelled', 'لغو شده'), ('completed', 'تکمیل شده'), ('refunded', 'عودت داده شده')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('online', 'پرداخت آنلاین'), ('bank_transfer', 'کارت به کارت'), ('cash', 'نقدی')], max_length=20, verbose_name='روش پرداخت')),
                ('payment_status', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('special_requests', models.TextField(blank=True, verbose_name='درخواست\u200cهای ویژه')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='تماس اضطراری')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن اضطراری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای رزرو')),
                ('departure_seats', models.ManyToManyField(related_name='departure_bookings', through='tours.SelectedSeat', to='tours.seat')),
                ('return_seats', models.ManyToManyField(blank=True, related_name='return_bookings', through='tours.SelectedReturnSeat', to='tours.seat')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour', verbose_name='تور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو تور',
                'verbose_name_plural': 'رزروهای تور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='selectedseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourbooking'),
        ),
        migrations.AddField(
            model_name='selectedreturnseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourbooking'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='tours.tourbooking'),
        ),
        migrations.CreateModel(
            name='BookingDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('discount_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف استفاده شده')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.discount')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='tours.tourbooking')),
            ],
            options={
                'verbose_name': 'تخفیف رزرو',
                'verbose_name_plural': 'تخفیف\u200cهای رزرو',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.CreateModel(
            name='TourDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.discount')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_discounts', to='tours.tour')),
            ],
            options={
                'verbose_name': 'تخفیف تور',
                'verbose_name_plural': 'تخفیف\u200cهای تور',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'verbose_name': 'تصویر تور',
                'verbose_name_plural': 'تصاویر تور',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='tours', to='tours.tourimage', verbose_name='گالری تصاویر'),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_tours', to='tours.transportation', verbose_name='وسیله نقلیه رفت'),
        ),
        migrations.AddField(
            model_name='tour',
            name='return_transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_tours', to='tours.transportation', verbose_name='وسیله نقلیه برگشت'),
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(verbose_name='تعداد ردیف\u200cها')),
                ('columns', models.PositiveIntegerField(verbose_name='تعداد ستون\u200cها')),
                ('aisle_after_column', models.PositiveIntegerField(default=0, verbose_name='راهرو پس از ستون')),
                ('transportation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='tours.transportation')),
            ],
            options={
                'verbose_name': 'طرح صندلی',
                'verbose_name_plural': 'طرح\u200cهای صندلی',
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tours.transportation'),
        ),
        migrations.AlterUniqueTogether(
            name='selectedseat',
            unique_together={('seat', 'is_departure')},
        ),
        migrations.AlterUniqueTogether(
            name='selectedreturnseat',
            unique_together={('seat', 'booking')},
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code', 'is_active'], name='tours_disco_code_78e411_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['valid_from', 'valid_to'], name='tours_disco_valid_f_f9f5c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tourdiscount',
            unique_together={('tour', 'discount')},
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['departure_datetime', 'is_active'], name='tours_tour_departu_e24781_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['tour_type', 'category'], name='tours_tour_tour_ty_da6aa8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('transportation', 'seat_number')},
        ),
    ]
