# Generated by Django 5.2.5 on 2025-10-30 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to=settings.AUTH_USER_MODEL, verbose_name='تایید شده توسط'),
        ),
        migrations.AddField(
            model_name='post',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AddField(
            model_name='post',
            name='discount_percentage',
            field=models.IntegerField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AddField(
            model_name='post',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_posts', to=settings.AUTH_USER_MODEL, verbose_name='ویراستاران'),
        ),
        migrations.AddField(
            model_name='post',
            name='has_discount',
            field=models.BooleanField(default=False, verbose_name='تخفیف دارد'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='توضیحات متا'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان متا'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('article', 'مقاله'), ('news', 'اخبار'), ('tutorial', 'آموزشی'), ('discount', 'تخفیف'), ('promotion', 'پرو موشن')], default='article', max_length=20, verbose_name='نوع پست'),
        ),
        migrations.AddField(
            model_name='post',
            name='scope',
            field=models.CharField(choices=[('internal', 'داخلی'), ('external', 'خارجی')], default='internal', max_length=10, verbose_name='حوزه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار تایید'), ('published', 'منتشر شده'), ('rejected', 'رد شده')], default='draft', max_length=10, verbose_name='وضعیت'),
        ),
    ]
