# Generated by Django 5.2.5 on 2025-10-29 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_traveler_name', models.CharField(max_length=100, verbose_name='نام مسافر اصلی')),
                ('main_traveler_email', models.EmailField(max_length=254, verbose_name='ایمیل مسافر اصلی')),
                ('main_traveler_phone', models.CharField(max_length=20, verbose_name='تلفن مسافر اصلی')),
                ('main_traveler_national_id', models.CharField(blank=True, max_length=20, verbose_name='کد ملی')),
                ('adult_count', models.PositiveIntegerField(default=1, verbose_name='تعداد بزرگسال')),
                ('child_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کودک')),
                ('infant_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نوزاد')),
                ('departure_date', models.DateField(verbose_name='تاریخ حرکت')),
                ('special_requests', models.TextField(blank=True, verbose_name='درخواست\u200cهای ویژه')),
                ('emergency_contact', models.TextField(blank=True, verbose_name='اطلاعات تماس اضطراری')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ پرداخت شده')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'پرداخت ناموفق'), ('refunded', 'عودت داده شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت رزرو')),
                ('reservation_code', models.CharField(max_length=15, unique=True, verbose_name='کد رزرو')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour', verbose_name='تور')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('nationality', models.CharField(max_length=50, verbose_name='ملیت')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='شماره پاسپورت')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'مسافر',
                'verbose_name_plural': 'مسافرین',
            },
        ),
    ]
