# Generated by Django 5.2.5 on 2025-10-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='سمت/شغل')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='شرکت')),
                ('testimonial_text', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=5, verbose_name='امتیاز')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tour', verbose_name='تور مربوطه')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['-created_date'],
            },
        ),
    ]
